
--STUDENT--
INSERT INTO STUDENT (STUDENT_ID,F_NAME,L_NAME,DOB,CITY) VALUES (1,'Pratik','Chatterjee','06/08/1990','Uluberia');
INSERT INTO STUDENT (STUDENT_ID,F_NAME,L_NAME,DOB,CITY) VALUES (2,'Pranati','Chatterjee','16/02/1991','Hyderabad');

--SUBJECT--
INSERT INTO SUBJECT (SUBJECT_ID,NAME,STUDENT_ID) VALUES (1,'Math',1);
INSERT INTO SUBJECT (SUBJECT_ID,NAME,STUDENT_ID) VALUES (2,'Power_System',1);
INSERT INTO SUBJECT (SUBJECT_ID,NAME,STUDENT_ID) VALUES (3,'Electrical_Machine',2);
