
--STUDENT--

DROP TABLE IF EXISTS STUDENT;

CREATE TABLE STUDENT
(
	STUDENT_ID int,
	F_NAME varchar2(255),
	L_NAME varchar2(255),
	DOB varchar2(10),
	CITY varchar2(255),
	CONSTRAINT PK_Student PRIMARY KEY (STUDENT_ID)
);

--SUBJECT--

DROP TABLE IF EXISTS SUBJECT;

CREATE TABLE SUBJECT
(
	SUBJECT_ID int,
	NAME varchar2(255),
	STUDENT_ID int,
	CONSTRAINT PK_Subject PRIMARY KEY (SUBJECT_ID),
	CONSTRAINT FK_Subject FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)
);

